table 'DX-BOM Structure & Counts for PO25@BR'
	lineageTag: 26bc4f49-65a8-45eb-913c-e05804df1bd0

	column TopParentMSPN
		dataType: string
		lineageTag: b277ceb8-abcc-408d-945f-fa0db82539f9
		summarizeBy: none
		sourceColumn: TopParentMSPN

		annotation SummarizationSetBy = Automatic

	column PartMSPN
		dataType: string
		lineageTag: bb15402a-f141-4d1c-9aac-d36adc63a42b
		summarizeBy: none
		sourceColumn: PartMSPN

		annotation SummarizationSetBy = Automatic

	column BOMQuantity
		dataType: int64
		formatString: 0
		lineageTag: 27ccb220-b7b1-41a5-aa14-96d3f9103651
		summarizeBy: none
		sourceColumn: BOMQuantity

		annotation SummarizationSetBy = Automatic

	column PartEmission
		dataType: double
		lineageTag: a6b24bcd-5022-475c-8823-7c87a78b37f0
		summarizeBy: none
		sourceColumn: PartEmission

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsLeaf
		dataType: int64
		formatString: 0
		lineageTag: 7f8d57c0-5e67-410d-875b-375a5b5fcc69
		summarizeBy: none
		sourceColumn: IsLeaf

		annotation SummarizationSetBy = Automatic

	partition 'DX-BOM Structure & Counts for PO25@BR' = m
		mode: import
		queryGroup: 'PO Data+HW#'
		source =
				let
				    Source = #"RQ, BR PRD",
				    AssemblyEmissionReports = Source{[Name="AssemblyEmissionReports"]}[Data],
				    #"Added Custom" = Table.AddColumn(AssemblyEmissionReports, "InPO25", each if List.Contains(#"MSPNs@FY25PO UAT@Nexus PPE", [TopParentMSPN]) or List.Contains(#"MSPNs@FY25PO UAT@Nexus PPE", [ParentMSPN]) or List.Contains(#"MSPNs@FY25PO UAT@Nexus PPE", [PartMSPN]) then 1 else 0),
				    #"Filtered Rows" = Table.SelectRows(#"Added Custom", each ([#"InPO25"] <> 0)),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Rows",{"TopParentMSPN", "PartMSPN", "BOMQuantity", "PartEmission", "IsLeaf"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns", {"PartMSPN"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

