table 'KPI-CHEM-Gap, BOM Parts of PO MSPNs w/o CHEM (vs Latest CHEMs)'
	lineageTag: 9a07d46d-0479-41dc-bdf4-c88055ef8b17

	column MSPN
		dataType: string
		lineageTag: 68b4e725-7a92-4018-b53f-9c370149e98d
		summarizeBy: none
		sourceColumn: MSPN

		annotation SummarizationSetBy = Automatic

	column PartName
		dataType: string
		lineageTag: 61a1896f-2f87-485b-ac5b-b5da8afaba36
		summarizeBy: none
		sourceColumn: PartName

		annotation SummarizationSetBy = Automatic

	column ClassPathItemType
		dataType: string
		lineageTag: b18e53a3-ec60-4789-a695-0aeef504df88
		summarizeBy: none
		sourceColumn: ClassPathItemType

		annotation SummarizationSetBy = Automatic

	column PartLabel
		dataType: string
		lineageTag: df06599f-ac4a-4ddd-95f6-11a798952c41
		summarizeBy: none
		sourceColumn: PartLabel

		annotation SummarizationSetBy = Automatic

	column kgCO2e/unit
		dataType: double
		lineageTag: 08821c4b-8b88-4a54-975b-fb7395fada6e
		summarizeBy: none
		sourceColumn: kgCO2e/unit

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column IsParentInGWPreport@NexusPPE
		dataType: int64
		formatString: 0
		lineageTag: da4ac4c1-2c8d-4d90-aa6b-aa03f001c116
		summarizeBy: none
		sourceColumn: IsParentInGWPreport@NexusPPE

		annotation SummarizationSetBy = User

	column ZeroPartTypeImpact
		dataType: int64
		formatString: 0
		lineageTag: 69668f3e-d07a-4486-835b-40940f82b0e6
		summarizeBy: none
		sourceColumn: ZeroPartTypeImpact

		annotation SummarizationSetBy = User

	column ZeroCHEMneedsToBeFixed
		dataType: int64
		formatString: 0
		lineageTag: 305ec0f4-9f00-4915-9506-998f8a61ff75
		summarizeBy: none
		sourceColumn: ZeroCHEMneedsToBeFixed

		annotation SummarizationSetBy = User

	column 'Need CHEM?'
		dataType: int64
		formatString: 0
		lineageTag: 4a2bb9ea-ba3c-4146-93d3-63ef00dd32d0
		summarizeBy: none
		sourceColumn: Need CHEM?

		annotation SummarizationSetBy = User

	partition 'KPI-CHEM-Gap, BOM Parts of PO MSPNs w/o CHEM (vs Latest CHEMs)' = m
		mode: import
		queryGroup: 'MSPNs Needing CHEM Across All BOM Levels of PO MSPNs'
		source =
				let
				    Source = #"Parts from All Levels of BOMs for PO MSPNs (from Report@BR PRD)",
				    #"Added Custom3" = Table.AddColumn(Source, "Has CHEM Value > 0?", each if List.Contains(MSPNswithNonNullNonZeroCHEM, [MSPN]) then 1 else 0, Int64.Type),
				    #"Filtered Rows1" = Table.SelectRows(#"Added Custom3", each ([#"Has CHEM Value > 0?"] = 0) and ([MSPN] <> "" and [MSPN] <> null)),
				    #"Merged Queries" = Table.NestedJoin(#"Filtered Rows1", {"MSPN"}, #"GWPbyPart@NexusPPE", {"MSPN"}, "GWPbyPart@NexusPPE", JoinKind.LeftOuter),
				    #"Expanded GWPbyPart@NexusPPE" = Table.ExpandTableColumn(#"Merged Queries", "GWPbyPart@NexusPPE", {"PartName", "ClassPathItemType", "PartLabel", "kgCO2e/unit"}, {"PartName", "ClassPathItemType", "PartLabel", "kgCO2e/unit"}),
				    #"Added Custom1" = Table.AddColumn(#"Expanded GWPbyPart@NexusPPE", "IsParentInGWPreport@NexusPPE", each if List.Contains(#"List, NonLeafMSPNs@PPE", [MSPN]) then 1 else 0, Int64.Type),
				    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "ZeroPartTypeImpact", each if List.Contains(#"List, ZeroPartTypeImpact@BR", [ClassPathItemType]) then 1 else 0, Int64.Type),
				    #"Added Custom4" = Table.AddColumn(#"Added Custom2", "ZeroCHEMneedsToBeFixed", each if [#"kgCO2e/unit"] = 0 and [ZeroPartTypeImpact] = 0 then 1 else 0, Int64.Type),
				    #"Added Custom5" = Table.AddColumn(#"Added Custom4", "Need CHEM?", each if [#"IsParentInGWPreport@NexusPPE"] = 1  or [ZeroPartTypeImpact] = 1 then 0 else 1, Int64.Type),
				    #"Removed Other Columns2" = Table.SelectColumns(#"Added Custom5",{"MSPN", "PartName", "ClassPathItemType", "PartLabel", "kgCO2e/unit", "IsParentInGWPreport@NexusPPE", "ZeroPartTypeImpact", "ZeroCHEMneedsToBeFixed", "Need CHEM?"})
				in
				    #"Removed Other Columns2"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

