table 'KPI-HW#-PO vs HWIS'
	lineageTag: e3303dde-9d4a-4555-bccc-572fc15c1142

	column FiscalYear
		dataType: int64
		formatString: 0
		lineageTag: 4fbdd8e9-3b00-4b55-9fe6-57cc3d9b9fc6
		summarizeBy: none
		sourceColumn: FiscalYear

		annotation SummarizationSetBy = User

	column ItemType
		dataType: string
		lineageTag: e5775578-1ab2-4ca2-aeb8-812880b48c99
		summarizeBy: none
		sourceColumn: ItemType

		annotation SummarizationSetBy = Automatic

	column Count
		dataType: int64
		formatString: #,0
		lineageTag: cb778d1f-e386-404c-8acd-301717079ad3
		summarizeBy: sum
		sourceColumn: Count

		annotation SummarizationSetBy = Automatic

	column Source
		dataType: string
		lineageTag: 54a86d65-6ef6-4123-9d01-1c9021aab8b3
		summarizeBy: none
		sourceColumn: Source

		annotation SummarizationSetBy = Automatic

	partition 'KPI-HW#-PO vs HWIS' = m
		mode: import
		queryGroup: 'QC.HW# (PO vs HWIS)'
		source =
				let
				    Source = Table.Combine({#"FY20-25 HWCount by Selected Class & Yr@HWInv", #"FY20-25 HWCount by Selected Class & Yr@CHEM & FY25PO UAT"}),
				    #"Split Column by Delimiter" = Table.SplitColumn(Source, "ClassPath", Splitter.SplitTextByEachDelimiter({"/"}, QuoteStyle.Csv, true), {"ClassPathItemType.1", "Rack Assembly Type"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Split Column by Delimiter",{"FY", "Rack Assembly Type", "Count", "Source"}),
				    #"Replaced Value" = Table.ReplaceValue(#"Removed Other Columns","Rack Assembly","",Replacer.ReplaceText,{"Rack Assembly Type"}),
				    #"Renamed Columns" = Table.RenameColumns(#"Replaced Value",{{"FY", "FiscalYear"}, {"Rack Assembly Type", "ItemType"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

